# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='fecha en la que se ha creado el objeto')),
                ('is_erased', models.BooleanField(default=False, verbose_name='Marca si se ha eliminado de forma l\xf3gica el objeto')),
                ('texto', models.CharField(max_length=250, verbose_name='contenido del post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que ha publicado el post')),
            ],
        ),
    ]
