# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del emoticono')),
                ('imagen', models.ImageField(upload_to=b'', verbose_name='Imagen del emoticono')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Post')),
            ],
            bases=('app.post',),
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['fecha_creacion']},
        ),
        migrations.AddField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.Post', verbose_name='Post al que responde este'),
        ),
        migrations.AddField(
            model_name='post',
            name='emote',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Emote', verbose_name='icono que acompa\xf1a al Post'),
        ),
    ]
