# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160524_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emote',
            name='imagen',
            field=models.ImageField(upload_to=b'emotes', verbose_name='Imagen del emoticono'),
        ),
    ]
